# Generated by Django 4.0.3 on 2022-04-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empID', models.IntegerField(primary_key=True, serialize=False)),
                ('empName', models.CharField(max_length=70)),
                ('empDesignation', models.CharField(max_length=70)),
            ],
        ),
    ]
