# Generated by Django 4.0.3 on 2022-04-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empDesignation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Employees.designation'),
        ),
    ]
